### ISSUE TITLE
Python library for huobi.com

### ISSUE THREAD

**Issue by sometastycake** [botcrypto-io/awesome-crypto-trading-bots#21]
I want to offer library for work with huobi.com cryptoexchange. Can add this library to list?
https://github.com/sometastycake/asynchuobi

**Comment by zatteo** [comment]
Yes! I need to clarify what is allowed and not allowed in this repository.

**Comment by sometastycake** [comment]
Repository have MIT license, if you mean it

**Comment by sometastycake** [comment]
For example, library have ability to receive stream data about cryptocurrency prices, orderbooks, recent trades, also about balance changing of account and last account trades.
And it supports rest api: api of orders, api of margin, api of account, etc

Repository have MIT license

**Comment by zatteo** [comment]
My goal is to create a list of tools, softwares and libraries useful for DIY trading bots makers. So your library is a perfect fit. I am even open to product **only if they focus on services for DIY trading bots makers**. So _no_ to mainstream commercial trading bots but _yes_ to commercial data provider or commercial technical indicator API. 

You can create a pull request and I will merge it.

**Comment by sometastycake** [comment]
Done

**Comment by zatteo** [comment]
Thank you!
