### ISSUE TITLE
Update Crypto Trading Bots Discussion telegram

### ISSUE THREAD

**Issue by rymdluo** [botcrypto-io/awesome-crypto-trading-bots#8]
Hi, regarding the telegram group "Crypto Trading Bots Discussion - A community for traders using algoritms, bots or auto trading software in crypto.", we have since moved to a new telegram group and started a forum to accompany it. The annoucement in the original telegram reflects the change as well.

Would appreciate it if you could update to reflect the changes:
- https://algotradingcrypto.com
- https://t.me/algotradingcrypto

**Comment by zatteo** [comment]
Hi :)

I just merged the PR from @tiagosiebler where it is updated.

https://github.com/botcrypto-io/awesome-crypto-trading-bots/pull/9
